### ISSUE TITLE
Hello, I wonder where I can download the images

### ISSUE THREAD

**Issue by SZhanZ** [zfchenUnique/Cops-Ref#4]
Hello, thanks for your promising work, it seems that you only provide the download link of annotation file, I can not find the link to download images, could you please provide it? Thanks in advance~

**Comment by zfchenUnique** [comment]
Hi, the images are borrowed from the original GQA dataset. You can download the images from the GQA's official website.

**Comment by zfchenUnique** [comment]
Questions are answered.
