### ISSUE TITLE
Download link does not work

### ISSUE THREAD

**Issue by pvoigtlaender** [zfchenUnique/Cops-Ref#5]
Hi,

Thanks for providing the great dataset!
It seems to me that the google drive links do no longer work, e.g. when I click on [https://drive.google.com/file/d/1bGqj_OweX2mawE387F7I9B4ZqDDSWBs0/view?usp=sharing](https://drive.google.com/file/d/1bGqj_OweX2mawE387F7I9B4ZqDDSWBs0/view?usp=sharing), I get an access denied message.
Can you please check this?

**Comment by zfchenUnique** [comment]
Hi, thanks for your interest and reminder of the broken links. I have updated all the links of the README.md .

**Comment by zfchenUnique** [comment]
the issue is fixed.
